<?php

declare(strict_types=1);

/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule\Form\EventListener;

use Zikula\MultiHookModule\Form\EventListener\Base\AbstractTranslationListener;

/**
 * Translation listener implementation class.
 */
class TranslationListener extends AbstractTranslationListener
{
    // feel free to add your customisation here
}
