<?php

declare(strict_types=1);

/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule\Entity;

use Zikula\MultiHookModule\Entity\Base\AbstractEntryTranslationEntity as BaseEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing entry translations.
 *
 * This is the concrete translation class for entry entities.
 *
 * @ORM\Entity(repositoryClass="Zikula\MultiHookModule\Entity\Repository\EntryTranslationRepository")
 * @ORM\Table(
 *     name="zikula_multih_entry_translation",
 *     options={"row_format":"DYNAMIC"},
 *     indexes={
 *         @ORM\Index(name="translations_lookup_idx", columns={
 *             "locale", "object_class", "foreign_key"
 *         })
 *     },
 *     uniqueConstraints={
 *         @ORM\UniqueConstraint(name="lookup_unique_idx", columns={
 *             "locale", "object_class", "field", "foreign_key"
 *         })
 *     }
 * )
 */
class EntryTranslationEntity extends BaseEntity
{
    // feel free to add your own methods here
}
