<?php
/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule\Form\Handler\Entry;

use Zikula\MultiHookModule\Form\Handler\Entry\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of editing forms.
 * It aims on the entry object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
