<?php
/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use Zikula\MultiHookModule\Entity\EntryEntity;

/**
 * Event base class for filtering entry processing.
 */
class AbstractFilterEntryEvent extends Event
{
    /**
     * @var EntryEntity Reference to treated entity instance.
     */
    protected $entry;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterEntryEvent constructor.
     *
     * @param EntryEntity $entry Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(EntryEntity $entry, array $entityChangeSet = [])
    {
        $this->entry = $entry;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return EntryEntity
     */
    public function getEntry()
    {
        return $this->entry;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
