<?php

declare(strict_types=1);

/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule\Form\Type;

use Zikula\MultiHookModule\Form\Type\Base\AbstractConfigType;

/**
 * Configuration form type implementation class.
 */
class ConfigType extends AbstractConfigType
{
    // feel free to extend the base form type class here
}
