<?php
/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule\Form\Type;

use Zikula\MultiHookModule\Form\Type\Base\AbstractEntryType;

/**
 * Entry editing form type implementation class.
 */
class EntryType extends AbstractEntryType
{
    // feel free to extend the entry editing form type class here
}
