<?php

/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\MultiHookModule\Event;

use Zikula\MultiHookModule\Event\Base\AbstractEntryPrePersistEvent;

/**
 * Event implementation class for filtering entry processing.
 */
class EntryPrePersistEvent extends AbstractEntryPrePersistEvent
{
    // feel free to extend the event class here
}
