<?php

/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\MultiHookModule\Form\Type\QuickNavigation;

use Zikula\MultiHookModule\Form\Type\QuickNavigation\Base\AbstractEntryQuickNavType;

/**
 * Entry quick navigation form type implementation class.
 */
class EntryQuickNavType extends AbstractEntryQuickNavType
{
    // feel free to extend the base form type class here
}
