<?php

/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\MultiHookModule\Menu\Base;

use Knp\Menu\FactoryInterface;
use Knp\Menu\ItemInterface;
use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Contracts\Translation\TranslatorInterface;
use Zikula\Common\Translator\TranslatorTrait;
use Zikula\ExtensionsModule\Api\ApiInterface\VariableApiInterface;
use Zikula\UsersModule\Api\ApiInterface\CurrentUserApiInterface;
use Zikula\UsersModule\Constant as UsersConstant;
use Zikula\MultiHookModule\Entity\EntryEntity;
use Zikula\MultiHookModule\MultiHookEvents;
use Zikula\MultiHookModule\Event\ConfigureItemActionsMenuEvent;
use Zikula\MultiHookModule\Event\ConfigureViewActionsMenuEvent;
use Zikula\MultiHookModule\Helper\ModelHelper;
use Zikula\MultiHookModule\Helper\PermissionHelper;

/**
 * Menu builder base class.
 */
class AbstractMenuBuilder
{
    use TranslatorTrait;
    
    /**
     * @var FactoryInterface
     */
    protected $factory;
    
    /**
     * @var EventDispatcherInterface
     */
    protected $eventDispatcher;
    
    /**
     * @var RequestStack
     */
    protected $requestStack;
    
    /**
     * @var PermissionHelper
     */
    protected $permissionHelper;
    
    /**
     * @var CurrentUserApiInterface
     */
    protected $currentUserApi;
    
    /**
     * @var VariableApiInterface
     */
    protected $variableApi;
    
    /**
     * @var ModelHelper
     */
    protected $modelHelper;
    
    public function __construct(
        TranslatorInterface $translator,
        FactoryInterface $factory,
        EventDispatcherInterface $eventDispatcher,
        RequestStack $requestStack,
        PermissionHelper $permissionHelper,
        CurrentUserApiInterface $currentUserApi,
        VariableApiInterface $variableApi,
        ModelHelper $modelHelper
    ) {
        $this->setTranslator($translator);
        $this->factory = $factory;
        $this->eventDispatcher = $eventDispatcher;
        $this->requestStack = $requestStack;
        $this->permissionHelper = $permissionHelper;
        $this->currentUserApi = $currentUserApi;
        $this->variableApi = $variableApi;
        $this->modelHelper = $modelHelper;
    }
    
    /**
     * Builds the item actions menu.
     */
    public function createItemActionsMenu(array $options = []): ItemInterface
    {
        $menu = $this->factory->createItem('itemActions');
        if (!isset($options['entity'], $options['area'], $options['context'])) {
            return $menu;
        }
    
        $entity = $options['entity'];
        $routeArea = $options['area'];
        $context = $options['context'];
        $menu->setChildrenAttribute('class', 'nav item-actions');
    
        $this->eventDispatcher->dispatch(
            new ConfigureItemActionsMenuEvent($this->factory, $menu, $options),
            MultiHookEvents::MENU_ITEMACTIONS_PRE_CONFIGURE
        );
    
        if ($entity instanceof EntryEntity) {
            $routePrefix = 'zikulamultihookmodule_entry_';
            
            if ($this->permissionHelper->mayEdit($entity)) {
                $title = $this->trans('Edit', 'zikulamultihookmodule');
                $menu->addChild($title, [
                    'route' => $routePrefix . $routeArea . 'edit',
                    'routeParameters' => $entity->createUrlArgs()
                ]);
                $menu[$title]->setLinkAttribute(
                    'title',
                    $this->trans('Edit this entry', 'zikulamultihookmodule')
                );
                $menu[$title]->setAttribute('icon', 'fa fa-edit');
                $title = $this->trans('Reuse', 'zikulamultihookmodule');
                $menu->addChild($title, [
                    'route' => $routePrefix . $routeArea . 'edit',
                    'routeParameters' => ['astemplate' => $entity->getKey()]
                ]);
                $menu[$title]->setLinkAttribute(
                    'title',
                    $this->trans('Reuse for new entry', 'zikulamultihookmodule')
                );
                $menu[$title]->setAttribute('icon', 'fa fa-files-o');
            }
        }
    
        $this->eventDispatcher->dispatch(
            new ConfigureItemActionsMenuEvent($this->factory, $menu, $options),
            MultiHookEvents::MENU_ITEMACTIONS_POST_CONFIGURE
        );
    
        return $menu;
    }
    
    /**
     * Builds the view actions menu.
     */
    public function createViewActionsMenu(array $options = []): ItemInterface
    {
        $menu = $this->factory->createItem('viewActions');
        if (!isset($options['objectType'], $options['area'])) {
            return $menu;
        }
    
        $objectType = $options['objectType'];
        $routeArea = $options['area'];
        $menu->setChildrenAttribute('class', 'nav view-actions');
    
        $this->eventDispatcher->dispatch(
            new ConfigureViewActionsMenuEvent($this->factory, $menu, $options),
            MultiHookEvents::MENU_VIEWACTIONS_PRE_CONFIGURE
        );
    
        $query = $this->requestStack->getMasterRequest()->query;
        $currentTemplate = $query->getAlnum('tpl', '');
        if ('entry' === $objectType) {
            $routePrefix = 'zikulamultihookmodule_entry_';
            if (!in_array($currentTemplate, [])) {
                $canBeCreated = $this->modelHelper->canBeCreated($objectType);
                if ($canBeCreated) {
                    if ($this->permissionHelper->hasComponentPermission($objectType, ACCESS_EDIT)) {
                        $title = $this->trans('Create entry', 'zikulamultihookmodule');
                        $menu->addChild($title, [
                            'route' => $routePrefix . $routeArea . 'edit'
                        ]);
                        $menu[$title]->setLinkAttribute('title', $title);
                        $menu[$title]->setAttribute('icon', 'fa fa-plus');
                    }
                }
                $routeParameters = $query->all();
                if (1 === $query->getInt('own')) {
                    $routeParameters['own'] = 1;
                } else {
                    unset($routeParameters['own']);
                }
                if (1 === $query->getInt('all')) {
                    unset($routeParameters['all']);
                    $title = $this->trans('Back to paginated view', 'zikulamultihookmodule');
                } else {
                    $routeParameters['all'] = 1;
                    $title = $this->trans('Show all entries', 'zikulamultihookmodule');
                }
                $menu->addChild($title, [
                    'route' => $routePrefix . $routeArea . 'view',
                    'routeParameters' => $routeParameters
                ]);
                $menu[$title]->setLinkAttribute('title', $title);
                $menu[$title]->setAttribute('icon', 'fa fa-table');
                if ($this->permissionHelper->hasComponentPermission($objectType, ACCESS_EDIT)) {
                    $routeParameters = $query->all();
                    if (1 === $query->getInt('own')) {
                        unset($routeParameters['own']);
                        $title = $this->trans('Show also entries from other users', 'zikulamultihookmodule');
                        $icon = 'users';
                    } else {
                        $routeParameters['own'] = 1;
                        $title = $this->trans('Show only own entries', 'zikulamultihookmodule');
                        $icon = 'user';
                    }
                    $menu->addChild($title, [
                        'route' => $routePrefix . $routeArea . 'view',
                        'routeParameters' => $routeParameters
                    ]);
                    $menu[$title]->setLinkAttribute('title', $title);
                    $menu[$title]->setAttribute('icon', 'fa fa-' . $icon);
                }
            }
        }
    
        $this->eventDispatcher->dispatch(
            new ConfigureViewActionsMenuEvent($this->factory, $menu, $options),
            MultiHookEvents::MENU_VIEWACTIONS_POST_CONFIGURE
        );
    
        return $menu;
    }
}
