<?php

/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\MultiHookModule\Listener;

use Zikula\MultiHookModule\Listener\Base\AbstractUsersListener;

/**
 * Event handler implementation class for events of the Users module.
 */
class UsersListener extends AbstractUsersListener
{
    // feel free to enhance the parent methods
}
