<?php

/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.5.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\MultiHookModule\Entity\Factory\Base;

use Zikula\MultiHookModule\Entity\EntryEntity;
use Zikula\MultiHookModule\Helper\ListEntriesHelper;
use Zikula\MultiHookModule\Helper\PermissionHelper;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * @var PermissionHelper
     */
    protected $permissionHelper;

    /**
     * @var ListEntriesHelper
     */
    protected $listEntriesHelper;

    public function __construct(
        PermissionHelper $permissionHelper,
        ListEntriesHelper $listEntriesHelper
    ) {
        $this->permissionHelper = $permissionHelper;
        $this->listEntriesHelper = $listEntriesHelper;
    }

    /**
     * Initialises a given entry instance.
     */
    public function initEntry(EntryEntity $entity): EntryEntity
    {
        $listEntries = $this->listEntriesHelper->getEntries('entry', 'entryType');
        foreach ($listEntries as $listEntry) {
            if (true === $listEntry['default']) {
                $entity->setEntryType($listEntry['value']);
                break;
            }
        }

        return $entity;
    }
    
    public function getListEntriesHelper(): ?ListEntriesHelper
    {
        return $this->listEntriesHelper;
    }
    
    public function setListEntriesHelper(ListEntriesHelper $listEntriesHelper = null): void
    {
        if ($this->listEntriesHelper !== $listEntriesHelper) {
            $this->listEntriesHelper = $listEntriesHelper;
        }
    }
}
