<?php

/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @see https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

declare(strict_types=1);

namespace Zikula\MultiHookModule\Form\Type\Field;

use Zikula\MultiHookModule\Form\Type\Field\Base\AbstractTranslationType;

/**
 * Translation field type implementation class.
 */
class TranslationType extends AbstractTranslationType
{
    // feel free to add your customisation here
}
