<?php
/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule\Listener;

use Zikula\MultiHookModule\Listener\Base\AbstractMailerListener;

/**
 * Event handler implementation class for mailing events.
 */
class MailerListener extends AbstractMailerListener
{
    // feel free to enhance the parent methods
}
