<?php
/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule\Event;

use Zikula\MultiHookModule\Event\Base\AbstractConfigureItemActionsMenuEvent;

/**
 * Event implementation class for extending item actions menu.
 */
class ConfigureItemActionsMenuEvent extends AbstractConfigureItemActionsMenuEvent
{
    // feel free to extend the event class here
}
