<?php
/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule\Event;

use Zikula\MultiHookModule\Event\Base\AbstractFilterEntryEvent;

/**
 * Event implementation class for filtering entry processing.
 */
class FilterEntryEvent extends AbstractFilterEntryEvent
{
    // feel free to extend the event class here
}
