services:
    zikula_multihook_module.collector.entry_provider_collector:
        class: Zikula\MultiHookModule\Collector\EntryProviderCollector
    zikula_multihook_module.collector.needle_collector:
        class: Zikula\MultiHookModule\Collector\NeedleCollector
    zikula_multihook_module.custom_twig_extension:
        class: Zikula\MultiHookModule\Twig\CustomTwigExtension
        arguments:
            - '@zikula_multihook_module.collector.entry_provider_collector'
            - '@zikula_multihook_module.collector.needle_collector'
        tags: ['twig.extension']
    zikula_multihook_module.multihook_entry_provider.default:
        class: Zikula\MultiHookModule\EntryProvider\DefaultEntryProvider
        arguments:
            - '@translator.default'
            - '@zikula_multihook_module.entity_factory'
        tags: ['zikula.multihook_entry_provider']
    zikula_multihook_module.multihook_needle.url:
        class: Zikula\MultiHookModule\Needle\UrlNeedle
        arguments:
            - '@translator.default'
            - '@request_stack'
            - "@=service('zikula_extensions_module.api.variable').get('ZikulaMultiHookModule', 'cssClassForExternalLinks', '')"
        tags: ['zikula.multihook_needle']
