services:
    # Entity factory
    zikula_multihook_module.entity_factory:
        class: Zikula\MultiHookModule\Entity\Factory\EntityFactory
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@zikula_multihook_module.entity_initialiser"
            - "@zikula_multihook_module.collection_filter_helper"
            - "@zikula_multihook_module.feature_activation_helper"
    
    # Entity initialiser
    zikula_multihook_module.entity_initialiser:
        class: Zikula\MultiHookModule\Entity\Factory\EntityInitialiser
        arguments:
            - "@zikula_multihook_module.permission_helper"
            - "@zikula_multihook_module.listentries_helper"
