services:
    # Helper services
    zikula_multihook_module.collection_filter_helper:
        class: Zikula\MultiHookModule\Helper\CollectionFilterHelper
        arguments:
            - "@request_stack"
            - "@zikula_multihook_module.permission_helper"
            - "@zikula_users_module.current_user"
            - "@=service('zikula_extensions_module.api.variable').get('ZikulaMultiHookModule', 'showOnlyOwnEntries', false)"
    
    zikula_multihook_module.controller_helper:
        class: Zikula\MultiHookModule\Helper\ControllerHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@form.factory"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_multihook_module.entity_factory"
            - "@zikula_multihook_module.collection_filter_helper"
            - "@zikula_multihook_module.permission_helper"
            - "@zikula_multihook_module.model_helper"
            - "@zikula_multihook_module.feature_activation_helper"
    
    zikula_multihook_module.entity_display_helper:
        class: Zikula\MultiHookModule\Helper\EntityDisplayHelper
        arguments:
            - "@translator.default"
            - "@zikula_multihook_module.listentries_helper"
    
    zikula_multihook_module.feature_activation_helper:
        class: Zikula\MultiHookModule\Helper\FeatureActivationHelper
    
    zikula_multihook_module.hook_helper:
        class: Zikula\MultiHookModule\Helper\HookHelper
        arguments:
            - "@hook_dispatcher"
        calls:
            - [setVariableApi, ["@zikula_extensions_module.api.variable"]]
    
    zikula_multihook_module.listentries_helper:
        class: Zikula\MultiHookModule\Helper\ListEntriesHelper
        arguments:
            - "@translator.default"
    
    zikula_multihook_module.model_helper:
        class: Zikula\MultiHookModule\Helper\ModelHelper
        arguments:
            - "@zikula_multihook_module.entity_factory"
    
    zikula_multihook_module.permission_helper:
        class: Zikula\MultiHookModule\Helper\PermissionHelper
        arguments:
            - "@service_container"
            - "@request_stack"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_users_module.current_user"
            - "@zikula_users_module.user_repository"
    
    zikula_multihook_module.translatable_helper:
        class: Zikula\MultiHookModule\Helper\TranslatableHelper
        arguments:
            - "@translator.default"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_settings_module.locale_api"
            - "@zikula_multihook_module.entity_factory"
    
    zikula_multihook_module.view_helper:
        class: Zikula\MultiHookModule\Helper\ViewHelper
        arguments:
            - "@twig"
            - "@twig.loader"
            - "@request_stack"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_core.internal.theme_filter"
            - "@zikula_multihook_module.controller_helper"
            - "@zikula_multihook_module.permission_helper"
    
    zikula_multihook_module.workflow_helper:
        class: Zikula\MultiHookModule\Helper\WorkflowHelper
        arguments:
            - "@translator.default"
            - "@workflow.registry"
            - "@logger"
            - "@zikula_users_module.current_user"
            - "@zikula_multihook_module.entity_factory"
            - "@zikula_multihook_module.listentries_helper"
            - "@zikula_multihook_module.permission_helper"
