services:
    zikula_multihook_module.link_container:
        class: Zikula\MultiHookModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_multihook_module.controller_helper"
            - "@zikula_multihook_module.permission_helper"
        tags: ['zikula.link_container']
    zikula_multihook_module.menu_builder:
        class: Zikula\MultiHookModule\Menu\MenuBuilder
        arguments:
            - "@translator.default"
            - "@knp_menu.factory"
            - "@event_dispatcher"
            - "@request_stack"
            - "@zikula_multihook_module.permission_helper"
            - "@zikula_users_module.current_user"
        tags:
            - { name: knp_menu.menu_builder, method: createItemActionsMenu, alias: zikulaMultiHookMenuItemActions }
