services:
    # Twig extension
    zikula_multihook_module.twig_extension:
        class: Zikula\MultiHookModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@zikula_multihook_module.entity_display_helper"
            - "@zikula_multihook_module.workflow_helper"
            - "@zikula_multihook_module.listentries_helper"
        public: false
        tags: ['twig.extension']
