<?php

declare(strict_types=1);

/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule\Entity\Repository;

use Zikula\MultiHookModule\Entity\Repository\Base\AbstractEntryTranslationRepository;

/**
 * Repository class used to implement own convenience methods for performing certain DQL queries.
 *
 * This is the concrete repository class for entry translation entities.
 */
class EntryTranslationRepository extends AbstractEntryTranslationRepository
{
    // feel free to add your own methods here
}
