<?php
/**
 * Multihook
 *
 * @copyright (c) 2001-now, Multihook Development Team
 * @link http://code.zikula.org/multihook
 * @version $Id$
 * @license GNU/GPL - http://www.gnu.org/copyleft/gpl.html
 * @package Multihook
 */

/**
 * the main administration function
 */
function MultiHook_admin_main()
{
    if(!SecurityUtil::checkPermission('MultiHook::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError('index.php');
    }

    $render = & pnRender::getInstance('MultiHook', false);
    $hmods = pnModAPIFunc('modules', 'admin', 'gethookedmodules', array('hookmodname' => 'MultiHook'));
    foreach($hmods as $hmod => $dummy) {
        $modid = pnModGetIDFromName($hmod);
        $moddata = pnModGetInfo($modid);
        $moddata['id'] = $modid;
        $hookedmodules[] = $moddata;
    }
    $render ->assign('hookedmodules', $hookedmodules);
    return $render ->fetch("mh_admin_main.html");
}

/**
 * add new item
 */
function MultiHook_admin_edit($args)
{
    // Security check
    if (!SecurityUtil::checkPermission('MultiHook::', '::', ACCESS_ADD)) {
        return LogUtil::registerPermissionError(pnModURL('MultiHook', 'admin', 'main'));
    }
    // load edithandler class from file
    Loader::requireOnce('modules/MultiHook/pnincludes/mh_admin_edithandler.class.php');

    // Create pnForm output object
    $pnf = FormUtil::newpnForm('MultiHook');

    // Return the output that has been generated by this function
    return $pnf->pnFormExecute('mh_admin_edit.html', new MultiHook_admin_edithandler());
}

/**
 * view items
 *
 *@params filter (int) 0=abbr, 1=acronyms, 2=links
 */
function MultiHook_admin_view()
{
    $dom = ZLanguage::getModuleDomain('MultiHook');

    if (!SecurityUtil::checkPermission('MultiHook::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError(pnModURL('MultiHook', 'admin', 'main'));
    }

    // Get parameters from whatever input we need
    $startnum = (int)FormUtil::getPassedValue('startnum', 0, 'GETPOST');
    $filter   = (int)FormUtil::getPassedValue('filter', -1, 'GETPOST');

    // The user API function is called
    $abacs = pnModAPIFunc('MultiHook',
                          'user',
                          'getall',
                          array('startnum' => $startnum,
                                'filter'   => $filter,
                                'numitems' => pnModGetVar('MultiHook',
                                                          'itemsperpage')));
    // set permission flags
    for($cnt=0; $cnt<count($abacs); $cnt++ ) {
        $abacs[$cnt]['edit'] = false;
        $abacs[$cnt]['delete'] = false;

        if (SecurityUtil::checkPermission('MultiHook::', "$abacs[$cnt][short]::$abacs[$cnt][aid]", ACCESS_EDIT)) {
            $abacs[$cnt]['edit'] = true;
            if (SecurityUtil::checkPermission('MultiHook::', "$abacs[$cnt][short]::$abacs[$cnt][aid]", ACCESS_DELETE)) {
                $abacs[$cnt]['delete'] = true;
            }
        }
    }
    $titles = array( __('Abbreviations list', $dom),
                     __('Acronyms list', $dom),
                     __('Links list', $dom),
                     __('Censored words list', $dom));

    // Create output object
    $render = & pnRender::getInstance('MultiHook', false, null, true);
    $render->assign('abacs', $abacs);
    $render->assign('title', $titles[$filter]);
    $render->assign('filter', $filter);
    $render->assign('abacscount', pnModAPIFunc('MultiHook', 'user', 'countitems', array('filter' => $filter)));
    return $render->fetch('mh_admin_view.html');
}

/**
 * modify configuration
 */
function MultiHook_admin_modifyconfig()
{

    if (!SecurityUtil::checkPermission('MultiHook::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError(pnModURL('MultiHook', 'admin', 'main'));
    }

    Loader::requireOnce('modules/MultiHook/pnincludes/mh_admin_modifyconfighandler.class.php');

    // Create output object
    $pnf = FormUtil::newpnForm('MultiHook');

    // Return the output that has been generated by this function
    return $pnf->pnFormExecute('mh_admin_config.html', new MultiHook_admin_modifyconfighandler());
}

/**
 * viewneedles
 *
 * shows a list of all needles supported by the MultiHook
 */
function MultiHook_admin_viewneedles()
{
    if (!SecurityUtil::checkPermission('MultiHook::', '::', ACCESS_ADMIN)) {
        return LogUtil::registerPermissionError(pnModURL('MultiHook', 'admin', 'main'));
    }

    $needles = pnModAPIFunc('MultiHook', 'admin', 'collectneedles');

    $render = & pnRender::getInstance('MultiHook', false);
    $render->assign('needles', $needles);
    return $render->fetch('mh_admin_viewneedles.html');
}
