zikulamultihookmodule:
    # define routing support for these controllers
    resource: "@ZikulaMultiHookModule/Controller"
    # enable support for defining routes by annotations
    type: annotation
