<?php

declare(strict_types=1);

/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule\DependencyInjection;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Zikula\Common\MultiHook\EntryProviderInterface;
use Zikula\Common\MultiHook\NeedleInterface;
use Zikula\MultiHookModule\DependencyInjection\Base\AbstractZikulaMultiHookExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class ZikulaMultiHookExtension extends AbstractZikulaMultiHookExtension
{
    public function load(array $configs, ContainerBuilder $container)
    {
        parent::load($configs, $container);

        $container->registerForAutoconfiguration(EntryProviderInterface::class)
            ->addTag('multihook_entry_provider')
        ;

        $container->registerForAutoconfiguration(NeedleInterface::class)
            ->addTag('zikula.multihook_needle')
        ;
    }
}
