<?php
/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule\DependencyInjection;

use Zikula\MultiHookModule\DependencyInjection\Base\AbstractZikulaMultiHookExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class ZikulaMultiHookExtension extends AbstractZikulaMultiHookExtension
{
    // custom enhancements can go here
}
