<?php
/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule;

use Zikula\MultiHookModule\Base\AbstractMultiHookEvents;

/**
 * Events definition implementation class.
 */
class MultiHookEvents extends AbstractMultiHookEvents
{
    // feel free to extend the events definition here
}
