<?php
/**
 * MultiHook.
 *
 * @copyright Zikula Team (Zikula)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Zikula Team <info@ziku.la>.
 * @link https://ziku.la
 * @version Generated by ModuleStudio 1.4.0 (https://modulestudio.de).
 */

namespace Zikula\MultiHookModule;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Zikula\MultiHookModule\Base\AbstractZikulaMultiHookModule;
use Zikula\MultiHookModule\DependencyInjection\Compiler\EntryProviderCollectorPass;
use Zikula\MultiHookModule\DependencyInjection\Compiler\NeedleCollectorPass;

/**
 * Module implementation class.
 */
class ZikulaMultiHookModule extends AbstractZikulaMultiHookModule
{
    /**
     * @inheritDoc
     */
    public function build(ContainerBuilder $container)
    {
        parent::build($container);

        $container->addCompilerPass(new EntryProviderCollectorPass());
        $container->addCompilerPass(new NeedleCollectorPass());
    }
}
